In [2]:
import numpy as np

In [5]:
A = np.array([[56.0,0.0,4.0,68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,13.5,99.0,0.9]])

print(A)

[[ 56.    0.    4.   68. ]
 [  1.2 104.   52.    8. ]
 [  1.8  13.5  99.    0.9]]


In [7]:
cal = A.sum(axis=0)
print(cal)

[ 59.  117.5 155.   76.9]


In [9]:
percentage = 100*A/cal
print(percentage)

[[94.91525424  0.          2.58064516 88.42652796]
 [ 2.03389831 88.5106383  33.5483871  10.40312094]
 [ 3.05084746 11.4893617  63.87096774  1.17035111]]
